Repository pre-onboarding/yamyam, pull requests merged in 2023-11, with the labels that each got.

#8 시군구 데이터 업로드 기능 구현
  build.gradle
  src/main/java/com/wanted/yamyam/api/location/controller/LocationController.java
  src/main/java/com/wanted/yamyam/api/location/dto/LocationUploadResponse.java
  src/main/java/com/wanted/yamyam/api/location/service/LocationService.java
  src/main/java/com/wanted/yamyam/domain/location/entity/Location.java
  src/main/resources/application.yml
  src/test/java/com/wanted/yamyam/FileUploadTest.java
  src/test/resources/application.yml
  src/test/resources/sgg_lat_lon.csv
Labels: enhancement

#12 시군구 데이터 전체 조회기능 구현
  src/main/java/com/wanted/yamyam/api/location/controller/LocationController.java
  src/main/java/com/wanted/yamyam/api/location/dto/LocationResponse.java
  src/main/java/com/wanted/yamyam/api/location/dto/LocationsListResponse.java
  src/main/java/com/wanted/yamyam/api/location/service/LocationService.java
  src/main/java/com/wanted/yamyam/domain/location/entity/Location.java
  src/test/java/com/wanted/yamyam/api/location/controller/LocationControllerTest.java
  src/test/resources/sgg_lat_lon.json
Labels: enhancement, backend

#14 맛집 평가 생성 기능 구현
  src/main/java/com/wanted/yamyam/api/review/controller/ReviewController.java
  src/main/java/com/wanted/yamyam/api/review/dto/ReviewRequest.java
  src/main/java/com/wanted/yamyam/api/review/dto/ReviewResponse.java
  src/main/java/com/wanted/yamyam/api/review/service/ReviewService.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreService.java
  src/main/java/com/wanted/yamyam/domain/review/repo/ReviewRepository.java
  src/main/java/com/wanted/yamyam/domain/store/repo/StoreRepository.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorCode.java
  src/test/java/com/wanted/yamyam/api/review/controller/ReviewControllerTest.java
  src/test/java/com/wanted/yamyam/api/store/service/StoreServiceTest.java
Labels: enhancement, backend

#10 feat: 맛집 목록 조회 기능
  src/main/java/com/wanted/yamyam/api/store/controller/StoreController.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreListResponse.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreResponse.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreService.java
  src/main/java/com/wanted/yamyam/domain/store/entity/Store.java
  src/main/java/com/wanted/yamyam/domain/store/repo/StoreRepository.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorCode.java
  src/test/java/com/wanted/yamyam/api/store/controller/StoreControllerTest.java
  src/test/java/com/wanted/yamyam/api/store/service/StoreServiceTest.java
Labels: backend

#20 시군구 목록 고도화를 위한 Redis 추가
  src/main/java/com/wanted/yamyam/api/location/service/LocationService.java
  src/main/java/com/wanted/yamyam/domain/location/entity/Location.java
  src/main/java/com/wanted/yamyam/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: enhancement, backend

#22 feat: 맛집 상세정보 조회 기능
  src/main/java/com/wanted/yamyam/api/review/dto/StoreByReviewListResponse.java
  src/main/java/com/wanted/yamyam/api/review/service/ReviewService.java
  src/main/java/com/wanted/yamyam/api/store/controller/StoreController.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreDetailAndReviewListResponse.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreDetailResponse.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreService.java
  src/main/java/com/wanted/yamyam/domain/review/repo/ReviewRepository.java
  src/test/java/com/wanted/yamyam/api/review/service/ReviewServiceTest.java
  src/test/java/com/wanted/yamyam/api/store/controller/StoreControllerTest.java
  src/test/java/com/wanted/yamyam/api/store/service/StoreServiceTest.java
Labels: backend

#28 맛집 상세정보 조회 고도화를 위해 캐싱 추가
  src/main/java/com/wanted/yamyam/api/review/service/ReviewService.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreService.java
  src/main/java/com/wanted/yamyam/domain/review/entity/Review.java
  src/main/java/com/wanted/yamyam/domain/store/entity/Store.java
  src/main/java/com/wanted/yamyam/global/config/RedisConfig.java
Labels: backend

#21 discord webhook을 이용한 점심 맛집 추천 기능 추가
  src/main/java/com/wanted/yamyam/YamyamApplication.java
  src/main/java/com/wanted/yamyam/api/member/task/MemberScheduledTask.java
  src/main/java/com/wanted/yamyam/api/store/dto/DiscordWebhook.java
  src/main/java/com/wanted/yamyam/api/store/dto/DiscordWebhookEmbed.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreResponse.java
  src/main/java/com/wanted/yamyam/domain/member/entity/Member.java
  src/main/java/com/wanted/yamyam/domain/member/repo/MemberRepository.java
  src/main/java/com/wanted/yamyam/global/config/AppConfig.java
  src/main/java/com/wanted/yamyam/global/config/DiscordConfig.java
  src/main/resources/application.yml
Labels: enhancement, backend

#11 데이터 수집
  build.gradle
  src/main/java/com/wanted/yamyam/api/store/dto/response/StoreSchedulerResponse.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreSchedulerService.java
  src/main/java/com/wanted/yamyam/domain/review/entity/Review.java
  src/main/java/com/wanted/yamyam/domain/store/entity/Store.java
  src/main/java/com/wanted/yamyam/domain/store/entity/StoreId.java
  src/main/java/com/wanted/yamyam/domain/store/repo/StoreRepository.java
  src/main/java/com/wanted/yamyam/domain/store/repo/StoreRepositoryCustom.java
  src/main/java/com/wanted/yamyam/domain/store/repo/StoreRepositoryCustomImpl.java
  src/main/java/com/wanted/yamyam/global/config/QuerydslConfig.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorCode.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorException.java
  src/main/java/com/wanted/yamyam/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: enhancement

#25 feat: 회원가입 & 로그인
  build.gradle
  src/main/java/com/wanted/yamyam/api/member/controller/MemberController.java
  src/main/java/com/wanted/yamyam/api/member/dto/MemberLoginResponse.java
  src/main/java/com/wanted/yamyam/api/member/dto/MemberRequest.java
  src/main/java/com/wanted/yamyam/api/member/service/MemberService.java
  src/main/java/com/wanted/yamyam/domain/member/entity/Member.java
  src/main/java/com/wanted/yamyam/domain/member/repo/MemberRepository.java
  src/main/java/com/wanted/yamyam/global/config/CorsConfig.java
  src/main/java/com/wanted/yamyam/global/config/JwtSecurityConfig.java
  src/main/java/com/wanted/yamyam/global/config/SecurityConfig.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorCode.java
  src/main/java/com/wanted/yamyam/global/jwt/CustomUserDetailsService.java
  src/main/java/com/wanted/yamyam/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/wanted/yamyam/global/jwt/JwtFilter.java
  src/main/java/com/wanted/yamyam/global/jwt/JwtTokenProvider.java
Labels: backend

#26 feat: 사용자 정보 업데이트 & 가져오기
  src/main/java/com/wanted/yamyam/api/member/controller/MemberController.java
  src/main/java/com/wanted/yamyam/api/member/dto/MemberLocationRequest.java
  src/main/java/com/wanted/yamyam/api/member/dto/MemberResponse.java
  src/main/java/com/wanted/yamyam/api/member/service/MemberService.java
  src/main/java/com/wanted/yamyam/domain/member/entity/Member.java
  src/main/java/com/wanted/yamyam/domain/member/repo/MemberRepository.java
  src/main/java/com/wanted/yamyam/global/exception/ErrorCode.java
Labels: backend

#27 feat: JWT
  src/main/java/com/wanted/yamyam/global/config/SecurityConfig.java
  src/main/java/com/wanted/yamyam/global/jwt/JwtFilter.java
  src/main/java/com/wanted/yamyam/global/jwt/JwtTokenProvider.java
Labels: backend

#32 맛집 상세정보, 맛집 리뷰 리스트 리팩토링
  src/main/java/com/wanted/yamyam/api/review/service/ReviewService.java
  src/main/java/com/wanted/yamyam/api/store/controller/StoreController.java
  src/main/java/com/wanted/yamyam/api/store/dto/StoreDetailResponse.java
  src/main/java/com/wanted/yamyam/api/store/service/StoreService.java
  src/main/java/com/wanted/yamyam/domain/review/repo/ReviewRepository.java
  src/test/java/com/wanted/yamyam/api/review/service/ReviewServiceTest.java
  src/test/java/com/wanted/yamyam/api/store/service/StoreServiceTest.java
Labels: backend

#31 맛집 평가에 사용자 id와 맛집 id 반영
  src/main/java/com/wanted/yamyam/api/review/controller/ReviewController.java
  src/main/java/com/wanted/yamyam/api/review/dto/ReviewResponse.java
  src/main/java/com/wanted/yamyam/api/review/service/ReviewService.java
Labels: enhancement, backend
